#!/usr/bin/env python3
"""
tools/font2c.py  -  Convert a PSF1 or PSF2 bitmap font into a C header
                    that the NumOS kernel embeds at build time.

Usage:
    python3 tools/font2c.py  path/to/font.psf  > src/drivers/font_data.h

The output header defines:
    static const uint8_t embedded_font_data[];
    static const size_t  embedded_font_size;

and sets FONT_DATA_AVAILABLE so font.c uses this data instead of its
built-in 8x16 fallback.

The script accepts both raw .psf files and gzip-compressed .psf.gz files
(which is what most Linux distributions ship).

Recommended free fonts
----------------------
Terminus  https://terminus-font.sourceforge.net/
  Sizes: 6x12, 8x14, 8x16, 10x20, 12x24, 14x28, 16x32
  Download the "psf" source archive and gunzip any .psf.gz inside.

Spleen    https://github.com/fcambus/spleen
  Sizes: 5x8, 8x16, 12x24, 16x32, 32x64
  Grab a release tarball; .psf files are included directly.

Linux system fonts (already on your machine):
  Debian/Ubuntu:  /usr/share/consolefonts/
  Arch/Fedora:    /usr/lib/kbd/consolefonts/
  Run: gunzip Lat2-Terminus16.psf.gz   (or any font you like)

GNU Unifont (full Unicode plane 0 coverage):
  https://unifoundry.com/unifont/
  Download unifont.psf.gz from the releases page.
"""

import sys
import os
import gzip
import struct

# ---------------------------------------------------------------------------
# PSF constants
# ---------------------------------------------------------------------------
PSF1_MAGIC = b'\x36\x04'
PSF2_MAGIC = b'\x72\xb5\x4a\x86'


def load_font_bytes(path: str) -> bytes:
    """Read a .psf or .psf.gz file and return the raw bytes."""
    if not os.path.isfile(path):
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)

    with open(path, 'rb') as f:
        raw = f.read()

    # Detect gzip by magic bytes
    if raw[:2] == b'\x1f\x8b':
        raw = gzip.decompress(raw)

    return raw


def probe_psf(data: bytes) -> dict:
    """
    Parse PSF1 or PSF2 header and return a dict with:
        version, width, height, bytes_per_glyph, num_glyphs, glyph_offset
    Raises ValueError if data is not a valid PSF font.
    """
    if data[:2] == PSF1_MAGIC:
        if len(data) < 4:
            raise ValueError("PSF1 file too short")
        mode      = data[2]
        char_size = data[3]
        num_glyphs = 512 if (mode & 0x01) else 256
        return {
            'version':        1,
            'width':          8,
            'height':         char_size,
            'bytes_per_glyph': char_size,
            'num_glyphs':     num_glyphs,
            'glyph_offset':   4,
        }

    if data[:4] == PSF2_MAGIC:
        if len(data) < 32:
            raise ValueError("PSF2 file too short")
        fields = struct.unpack_from('<IIIIIIII', data, 0)
        header_size = fields[2]
        num_glyphs = fields[4]
        bytes_per_glyph = fields[5]
        height = fields[6]
        width = fields[7]
        return {
            'version':        2,
            'width':          width,
            'height':         height,
            'bytes_per_glyph': bytes_per_glyph,
            'num_glyphs':     num_glyphs,
            'glyph_offset':   header_size,
        }

    raise ValueError("Not a PSF1 or PSF2 font (bad magic bytes)")


def emit_c_header(data: bytes, info: dict, source_path: str) -> None:
    """Print the C header to stdout."""
    src_name = os.path.basename(source_path)
    total    = len(data)

    print("/*")
    print(f" * font_data.h  -  auto-generated by tools/font2c.py")
    print(f" * Source : {src_name}")
    print(f" * Format : PSF{info['version']}")
    print(f" * Size   : {info['width']} x {info['height']} pixels")
    print(f" * Glyphs : {info['num_glyphs']}")
    print(f" * Blob   : {total} bytes")
    print(" *")
    print(" * DO NOT EDIT - regenerate with:")
    print(f" *   python3 tools/font2c.py {source_path} > src/drivers/font_data.h")
    print(" */")
    print()
    print("#ifndef FONT_DATA_H")
    print("#define FONT_DATA_H")
    print()
    print("/* Signals font.c to use this data instead of the built-in fallback. */")
    print("#define FONT_DATA_AVAILABLE 1")
    print()
    print(f"static const uint8_t embedded_font_data[{total}] = {{")

    # 12 bytes per output row
    COLS = 12
    for i in range(0, total, COLS):
        chunk = data[i:i + COLS]
        line  = ', '.join(f'0x{b:02X}' for b in chunk)
        if i + COLS < total:
            line += ','
        # Add a comment every 256 bytes showing the offset
        if i % 256 == 0:
            print(f"    /* offset 0x{i:04X} */")
        print(f"    {line}")

    print("};")
    print()
    print(f"static const size_t embedded_font_size = {total}UL;")
    print()
    print("#endif /* FONT_DATA_H */")


def main():
    if len(sys.argv) != 2 or sys.argv[1] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0 if len(sys.argv) == 1 else 1)

    path = sys.argv[1]
    data = load_font_bytes(path)

    try:
        info = probe_psf(data)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[font2c] PSF{info['version']}  {info['width']}x{info['height']}"
          f"  {info['num_glyphs']} glyphs  {len(data)} bytes",
          file=sys.stderr)

    emit_c_header(data, info, path)


if __name__ == '__main__':
    main()
